### PR TITLE
Update 2019-05-21T13:55:54.904Z

### PR DESCRIPTION
**Pull request by Scapenighter**
I am just a bit unsure but I am creating pull request anyways...

### CODE REVIEW

**Comment by itowlson** [comment]
Hi @Scapenighter, thanks for your contribution but I'm not sure what you're trying to achieve here.  This seems like it may have been forked from the `gh-pages` branch which is an autogenerated Web site, and it appears to delete most of the files that make up the extension.  Could you clarify what you're trying to fix or improve, and we can maybe help you rework your pull request?  Thanks!

**Comment by itowlson** [comment]
I noticed that the PR as sent is actually merging the `gh-pages` branch in the main Azure repo into the `master` branch.  This definitely isn't going to do what you want - the `gh-pages` branch contains a generated Web site and is always derived from `master`, not vice versa; plus, the Azure repo won't contain any of your changes.  What you need to do is this:

* fork the repo into your own GitHub account
* take a branch off `master`
* make changes on that branch
* push the branch with changes to _your_ fork
* create a pull request from the pushed branch in your fork

Hope this makes sense - happy to provide more detail on any of these steps if that would help.

**Comment by Scapenighter** [comment]
Sorry about that .I had few to many things going on on my computer and mixed a few things up in the process...Right now I am decluttering my computer before I do any more work... hopefully my next pull request make more sense, not just for me, but for you too...I am a little new at this and still have a lot to learn...Thank you for taking the time to point out the right direction, I really appreciate it...👍😁😎

Sent from my iPhone

On Feb 9, 2020, at 3:02 PM, itowlson <notifications@github.com> wrote:

﻿

I noticed that the PR as sent is actually merging the gh-pages branch in the main Azure repo into the master branch. This definitely isn't going to do what you want - the gh-pages branch contains a generated Web site and is always derived from master, not vice versa; plus, the Azure repo won't contain any of your changes. What you need to do is this:

  *   fork the repo into your own GitHub account
  *   take a branch off master
  *   make changes on that branch
  *   push the branch with changes to your fork
  *   create a pull request from the pushed branch in your fork

Hope this makes sense - happy to provide more detail on any of these steps if that would help.

**Comment by itowlson** [comment]
@Scapenighter Since you alluded to sending stuff in your next PR rather than amending this one (which I'm not sure is even possible), I'm closing this one if that's okay. If you do want to keep this one going, please feel free to reopen; otherwise, looking forward to your contribution and thanks in advance!

**Pull request closed without merging**
