### PR TITLE
Bug #175: Add the missing 'type' key for object value property to fix the validation issue

### PR DESCRIPTION
**Pull request by testforstephen**
Fix bug https://github.com/Azure/vscode-kubernetes-tools/issues/175

Before:
image

Now:
image

Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

### CODE REVIEW

**Comment by itowlson** [comment]
Is the `"type": "object"` attribute added by hand or using a tool?  How will we maintain this when we take an updated Swagger file from upstream?

**Comment by andxu** [comment]
"type: object" was missing from origin kubernetes swagger json : https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

**Comment by testforstephen** [comment]
For this PR part, i wrote a tiny js program to amend the missing `type` for object value. 

The original schema is copied from the link above, and @andxu has a program to customize the scope for enum type.  He will upload the program code for maintainance.

**Comment by andxu** [comment]
I will create a PR adding my program to modify schema to this repository, then in almost cases, we can keep schema up to date automatically

**Comment by sallyur** [comment]
We used the build 4626 verified the PR #228 passed.

**Comment by andxu** [comment]
The content of swagger-v1.9.3.json comes from:
`https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.9.3-standalone/_definitions.json`
and I have also created the PR to collect known enums from types.go of  kubernetes source code.
https://github.com/Azure/vscode-kubernetes-tools/pull/243

**Pull request merged**
