### PR TITLE
Show chart and app version in Helm release history

### LINKED ISSUE #881: Feature: add chart version and other meta to helm releases view
Would you please add at least the cart version to the helm Releases (history) view, to get detailed information what release one might want to restore. The chart release ids which are just increasing number ate not helpful at al.

image
image

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #881.

This has the info as a tooltip - is that going to work for you @cforce?  If not let's discuss good ways of presenting this extra info.

cc @shreyaskarnik as I don't seem to be able to add you as a reviewer

### CODE REVIEW

**Comment by shreyaskarnik** [comment]
@itowlson checking out the PR. Also on a sidenote apologies for https://github.com/Azure/vscode-kubernetes-tools/pull/877 did not realize I was changing contracts. :(  Thanks for catching and fixing.

**Comment by shreyaskarnik** [comment]
@itowlson Works great!

**Comment by shreyaskarnik** [comment]
In terms of the helm release tree there is this example 
image 

which I like from the docker extension where additional information can be displayed a little differently with font weights. Maybe the uptime can be displayed with a different font weight which can draw more attention to release number prompting the hover or click to gather more information.

**Comment by itowlson** [comment]
I really like this idea.  That 'less prominent' effect is done via the `TreeItem.description` property so this should be a fairly easy change.  Do you suggest I roll it into this PR, or would you prefer to hold off and do it as a separate enhancement?

**Comment by shreyaskarnik** [comment]
@itowlson either way would work fine., I want to be respectful of your time. Reason I did bring this example up was to potentially use it in other tree items.

**Comment by itowlson** [comment]
@shreyaskarnik This is slightly off topic, but looking at the code, it looks like clicking a history node loads the _current_ release, not the one that was selected?  `helm get all` does have a `--revision` option - should we pass that?

**Comment by shreyaskarnik** [comment]
@itowlson checking this out.

**Comment by itowlson** [comment]
@shreyaskarnik Here is how it looks with the description - is this what you envisaged and if so are you happy with it?

image

**Comment by shreyaskarnik** [comment]
@itowlson that looks great! I can repro the behaviour with clicking of helm history node and it shows only the last node. This is due to the fact that `getChildren` is empty and the command you proposed will fix that.

**Comment by itowlson** [comment]
Thanks!  I don't want the 'load correct release' fix to get squashed in with the metadata and formatting changes, so I've raised #884 to track that.

**Review by lstocchi — APPROVED** [review]

**Pull request merged**
