### PR TITLE
Fix webpack for logs view

### PR DESCRIPTION
**Pull request by itowlson**
@lstocchi Tried this with a VSIX and it seemed okay.  If you are still up and have time to look, that would be great, otherwise I will ship on the basis that I can't possibly make things worse... _dramatic chord_

### CODE REVIEW

**Comment by lstocchi** [comment]
@itowlson reviewing it now

**Comment by lstocchi** [comment]
@itowlson sorry ivan i was trying a thing on my local repo and i accidentally pushed a change on your branch. Before to do some other mistake can you please revert it? I don't have enough permission to force push. I need a coffee lol.

**Comment by lstocchi** [comment]
I guess it's late for you now but the command works fine. The problem is with the view css. Investigating on it
image

**Comment by lstocchi** [comment]
@itowlson i don't know what kind of magic is going on here but for some reason, in my logs view PR, vscode adds a margin between two elements that it doesn't exist after packaging in vsix.

Below you can see there is no css rule but a space between two elements is added by default. I'm going to write an explicit css rule for it as i have no other idea to solve it quickly.

margin-invisible

**Comment by itowlson** [comment]
Okay, do you want me to hold off on this while you deal to the CSS, or revert your change and go with it as it is?

**Comment by lstocchi** [comment]
@itowlson revert my change for sure. Thanks and sorry. I'm doing a final test with a built vsix but i'm pretty sure to have fixed it. If it works i'm going to create a PR. If you can wait 5 mins it would be awesome, so we can merge the css fix, this PR and retry to release

**Comment by itowlson** [comment]
No worries - if yours works I'll scrap this one and do a release with yours instead.  Thanks heaps!

**Comment by itowlson** [comment]
Superseded by #934.

**Pull request closed without merging**
