### PR TITLE
Read the install locations from User and default configuration to decide whether the dependencies are installed or not

### PR DESCRIPTION
**Pull request by rakeshvanga**
**Description:**
This PR fixes the issue where the dependencies(kubectl, helm, minikube) are not being downloaded in remote-containers automatically. Currently in #543, manual workaround are specified to unblock the users but this PR would remove the need to have a manual workarounds.
**How it is being fixed:**
Once the install dependencies button is clicked, on a fresh machine the binaries are being downloaded to /home/username/.vs-kubernetes/tools/< toolname >/< toolBinary >. After the download is completed (for example in installKubectl ), the path of the tool is updated in the config values at Global, Workspace & WorkspaceFolder level using `addPathToConfig`.
Previously the values are being retrieved from the custom config values.

### CODE REVIEW

**Comment by squillace** [comment]
Luca, you want to look, or not?

**Comment by lstocchi** [comment]
@squillace sure :+1:

**Comment by rakeshvanga** [comment]
> LGTM, tested and works fine. Thanks!!

@lstocchi Thanks for reviewing the PR. I'm good with the changes. Can you merge these changes?

**Comment by Tatsinnit** [comment]
💡thought share: just adding small idea to double check, but I hope the binary issue and file permission issue will not arise in these 2 new location. I think it will not, but worth to make sure: #922 and #850 , thanks heaps 🙏

**Comment by rakeshvanga** [comment]
> 💡thought share: just adding small idea to double check, but I hope the binary issue and file permission issue will not arise in these 2 new location. I think it will not, but worth to make sure: #922 and #850 , thanks heaps 🙏

@Tatsinnit, Thanks for pointing out the other scenarios. This change will not affect the logic introduced in the PRs you have shared. It will continue to set the right permissions for the executables.

**Pull request merged**
