### PR TITLE
Rework Azure CLI version regex to be compatible with 2.0.58

### LINKED ISSUE #475: Always show "Error checking prerequisites" when exec Create Kubernetes Cluster wizard
```
vscode: 1.31.1
kubernetes extension: 0.1.16
```

When exec "Create Kubernetes Cluster" wizard, it always show the error below even though i installed the azure-cli 2.0.58.

```
null
Error checking prerequisites
The Azure command line failed. See below for the error message. You may need to:

Log into the Azure CLI (run az login in the terminal)
Install the Azure CLI (see the instructions for your operating system)
Configure Kubernetes from the command line using the az acs or az aks command
Details

Azure CLI 2.0 not found - install Azure CLI 2.0 and log in

```

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #475.

### CODE REVIEW

**Comment by jvermast** [comment]
Is it possible this broke again? getting the same error on 2.0.65

C:\windows\system32>az --version
azure-cli                         2.0.65

Error checking prerequisites
The Azure command line failed. See below for the error message. You may need to:

Log into the Azure CLI (run az login in the terminal)
Install the Azure CLI (see the instructions for your operating system)
Configure Kubernetes from the command line using the az acs or az aks command
Details

Azure CLI 2.0 not found - install Azure CLI 2.0 and log in

**Comment by itowlson** [comment]
Aaugh, taking a look.  Thanks for the heads up @jvermast.

**Comment by itowlson** [comment]
@jvermast It's working for me on 2.0.66 (which is what the download page gave me).  I'm not sure why you might be seeing an error here...

**Comment by jvermast** [comment]
Very odd... I'll try 66. Had a couple guys on my team with the same error on 65. I'm sure it's something were doing...but az cli is definitely working. Very odd indeed.

I'll let you know what I figure out

**Comment by itowlson** [comment]
Thanks.  If you feel confident, you could try running the extension from source (clone the git repo, load into VS Code and hit F5) and set breakpoints on the `azureCliVersion` command (in `src/components/clusterprovider/azure/azure.ts` line 83) to see why it's not working.  (You don't need to uninstall the marketplace extension to do this - the debuggee extension will overwrite it _temporarily and in the debug environment only_.)  But yeah, let me know if you keep running into it and I'll see if I can dig out 65 and try again.

**Comment by jvermast** [comment]
Gave that a shot, I see azVersion is null so it throws the Azure CLI 2.0 not found. 


Az looks fine itself...
PS C:\X\vscode-kubernetes-tools> az --version
azure-cli                         2.0.65

acr                                2.2.7
acs                                2.4.2
advisor                            2.0.0
ams                                0.4.6
appservice                        0.2.20
backup                             1.2.4
batch                              4.0.1
batchai                            0.4.9
billing                            0.2.1
botservice                         0.2.1
cdn                                0.2.3
cloud                              2.1.1
cognitiveservices                  0.2.5
command-modules-nspkg               2.0.2
configure                         2.0.23
consumption                        0.4.3
container                         0.3.17
core                              2.0.65
cosmosdb                          0.2.10
deploymentmanager                  0.1.0
dla                                0.2.5
dls                                0.1.9
dms                                0.1.3
eventgrid                          0.2.3
eventhubs                          0.3.6
extension                          0.2.5
feedback                           2.2.1
find                               0.3.3
hdinsight                          0.3.4
interactive                        0.4.4
iot                                0.3.9
iotcentral                         0.1.6
keyvault                          2.2.15
kusto                              0.2.2
lab                                0.1.7
maps                               0.3.4
monitor                           0.2.14
natgateway                         0.1.0
network                            2.5.0
nspkg                              3.0.3
policyinsights                     0.1.3
privatedns                         1.0.1
profile                            2.1.5
rdbms                             0.3.11
redis                              0.4.3
relay                              0.1.4
reservations                       0.4.2
resource                          2.1.14
role                               2.6.2
search                             0.1.1
security                           0.1.1
servicebus                         0.3.5
servicefabric                     0.1.19
signalr                            1.0.0
sql                                2.2.4
sqlvm                              0.1.1
storage                            2.4.2
telemetry                          1.0.2
vm                                2.2.21

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\X\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

**Comment by jvermast** [comment]
I looked into it some more. 

If I remove  || sr.stderr from line 85 it works as expected. I see the following at the end of my "az --version" 

"WARNING: Unable to check if your CLI is up-to-date. Check your internet connection."

Which I believe is what's causing the issue, even though its really not an issue. :D

**Comment by itowlson** [comment]
Ah, okay.  I think we had experiences perhaps with older versions where it could fail but still return exit code 0, so we had to check stderr as well.  That might have been for the service plug-ins though (from a previous life I seem to recall that it buried errors from Azure Batch.)  Let me raise a new issue for this and get it fixed.

Thanks for digging into this - not something we could have easily reproduced and I appreciate the time you put in helping us make things better.

**Comment by itowlson** [comment]
@jvermast Should be fixed in 1.0.1, up on Marketplace now.

**Pull request merged**
