### PR TITLE
Publish 1.3.5

### PR DESCRIPTION
**Pull request by itowlson**
Since everybody has been nice this year 🎅

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by lstocchi** [comment]
@itowlson I would also include this PR https://github.com/Azure/vscode-kubernetes-tools/pull/1019 to this release if it's good. Please give it a look. Thanks!!

**Review by bnookala — APPROVED** [review]

**Comment by itowlson** [comment]
Rebased to include #1019 and #746 and changelog updated.

**Review by bnookala — APPROVED** [review]

**Review by squillace — APPROVED** [review]

**Review by lstocchi — APPROVED** [review]

**Comment by squillace** [comment]
@itowlson do you care to push the publish button, or shall I? I mean, we'll have to test the token lifetime again one way or the other. :-)

**Pull request merged**
