### PR TITLE
Add several tslint rules

### PR DESCRIPTION
**Pull request by itowlson**
Adds several tslint rules as per #165.

### CODE REVIEW

**Comment by itowlson** [comment]
Okay, I admit it, I claimed this one so that I wouldn't be the one who had to review every single whitespace change across 40+ files.

**Comment by brendandburns** [comment]
I merged a couple other of your PRs so this needs a rebase...

**Comment by itowlson** [comment]
Rebased

**Comment by bnookala** [comment]
Looks good!

**Pull request merged**
