### PR TITLE
Add limit logs support 

### PR DESCRIPTION
**Pull request by Devjeel**
- [✔] Add limit logs support

- [✔] Update README

- [  ] (Help needed) --since value provided explicitly. eg `--since=5m` . Any need to make it user inputtable ? 

Fix to : #765

### CODE REVIEW

**Comment by Devjeel** [comment]
@lstocchi Yes, you are right. hard coded values are not good. 

Please share ideas on how to allow user to input value. 🚀
@itowlson

**Comment by itowlson** [comment]
I did wonder if we could add a drop-down to the logs webview to specify the 'since' interval, but I don't think that works well unless we default to limiting - otherwise the webview displays everything first, and then you get to say "uh no only the last 30 seconds" which isn't a great user experience!

But a possible development of that would be to do something like this:

* Get rid of separate Show, Follow and Limit Logs commands; just have a Logs command
* When the webview starts up, it does _not_ display logs immediately.  Instead it displays only the toolbar, with options like:
  * Show or Follow
  * Time period to show (e.g. 1/2/5/10/20/30 mins/1/2/6/24/48 hours/All)
  * Filter options (as present)
* The toolbar also has a Go button
* And we fetch the logs when the user presses the Go button

Thoughts?

One issue with this is for folks who prefer their logs in the terminal.  I guess we could have another option in the toolbar to send the logs to the terminal (which would disable the Filter options... unless anyone fancies constructing the right grep incantation and executing a piped command), but not sure that's the right experience.

If we don't want something that radical then yes, a VS Code quick pick is the way to go to select the time interval.  But I'm not sure we want to force users to go through that quick pick every time they want to view logs...

**Comment by itowlson** [comment]
Thinking about this I am tempted by the Radical Webview option because it gives us somewhere to put future knobs too, rather than requiring more commands and more quick picks for more and more log options.

Also, the "which container do you want to see logs for" quick pick (for multi-container pods) could go in the toolbar too.

**Comment by adamrushuk** [comment]
> When the webview starts up, it does _not_ display logs immediately. Instead it displays only the toolbar, with options like:
> * Show or Follow
> * Time period to show (e.g. 1/2/5/10/20/30 mins/1/2/6/24/48 hours/All)
> * Filter options (as present)

This sounds like the best way forward to me 👍 

> I guess we could have another option in the toolbar to send the logs to the terminal

I also really like this idea.

However it's implemented, having a way to limit log output will be a huge win for this extension.

**Comment by lstocchi** [comment]
> Thinking about this I am tempted by the Radical Webview option because it gives us somewhere to put future knobs too, rather than requiring more commands and more quick picks for more and more log options.
> 
> Also, the "which container do you want to see logs for" quick pick (for multi-container pods) could go in the toolbar too.

I agree with this. It could be quite handy to have a unique webview to manage/add other features in future. 

> If we don't want something that radical then yes, a VS Code quick pick is the way to go to select the time interval. But I'm not sure we want to force users to go through that quick pick every time they want to view logs...

It's a radical solution but if we don't do it now I have the feeling we will end up with this discussion again in the future. So, better to tackle it now. 
I also don't like much showing a quick pick before to show logs but this was the only idea i had. If we have a better solution, we should go for that.

> But a possible development of that would be to do something like this:
> 
> * Get rid of separate Show, Follow and Limit Logs commands; just have a Logs command
> * When the webview starts up, it does _not_ display logs immediately.  Instead it displays only the toolbar, with options like:
>   
>   * Show or Follow
>   * Time period to show (e.g. 1/2/5/10/20/30 mins/1/2/6/24/48 hours/All)
>   * Filter options (as present)
> * The toolbar also has a Go button
> * And we fetch the logs when the user presses the Go button
> 
> Thoughts?

+1

**Comment by itowlson** [comment]
@Devjeel Sorry, I had not thought about these complexities when I tagged it as a good first issue!  I hope you're still keen to work on it?!

**Comment by Devjeel** [comment]
@itowlson this sounds great ;) . Let me give it a try. If you can suggest how to implement webview/toolbar type for logs option ?

**Comment by itowlson** [comment]
@Devjeel The toolbar is already in there with the filter functionality and a "scroll to bottom" button.  You should be able to add new controls to that existing toolbar.  The tricky bit will, I think, be deferring the fetch of the logs until the user hits the Go button.

**Comment by itowlson** [comment]
@Devjeel Forgot to say, thanks for doing this!

**Comment by lstocchi** [comment]
Any news on this PR @Devjeel ? Do you want us to handle it?

**Comment by Devjeel** [comment]
> 
> 
> Any news on this PR @Devjeel ? Do you want us to handle it?

Hi @lstocchi , got caught in my own stuff. Please assign it to someone else. Thanks.

**Comment by lstocchi** [comment]
Ok thank you @Devjeel !!

**Pull request closed without merging**
